import { ApiProperty } from '@nestjs/swagger';
import { PaginationDto } from '../../../../shared/interfaces/http/dto';
import * as actionEntity from '../../../domain/aggregates/action.aggregate';
import type { ActionStatus } from '../../../domain/value-objects/action-status.vo';
import type { ActionType } from '../../../domain/value-objects/action-type.vo';
import { ActionAttackDto } from './action-attack.dto';
import { ActionManeuverDto } from './action-maneuver.dto';
import { ActionMovementDto } from './action-movement.dto';

export class ActionDto {
  @ApiProperty({ description: 'Action identifier', example: 'action-123' })
  id: string;

  @ApiProperty({ description: 'Game identifier', example: 'game-456' })
  gameId: string;

  @ApiProperty({ description: 'Action status', example: 'declared' })
  status: ActionStatus;

  @ApiProperty({ description: 'Character identifier', example: 'character-789' })
  actorId: string;

  @ApiProperty({ description: 'The round number in which the action takes place', example: 1 })
  round: number;

  @ApiProperty({ description: 'Action type', example: 'attack' })
  actionType: ActionType;

  @ApiProperty({ description: 'Phase start', example: 1 })
  phaseStart: number;

  @ApiProperty({ description: 'Phase end', example: 1 })
  phaseEnd: number | undefined;

  @ApiProperty({ description: 'Action points', example: 2 })
  actionPoints: number | undefined;

  @ApiProperty({ description: 'Action movement', type: ActionMovementDto, required: false })
  movement: ActionMovementDto | undefined;

  @ApiProperty({ description: 'Action maneuver', type: ActionManeuverDto, required: false })
  maneuver: ActionManeuverDto | undefined;

  @ApiProperty({ description: 'Action attacks', type: [ActionAttackDto], required: false })
  attacks: ActionAttackDto[] | undefined;

  @ApiProperty({ description: 'Fatigue generated by the action', example: 5, required: false })
  fatigue: number | undefined;

  @ApiProperty({ description: 'Action description' })
  description?: string;

  static fromEntity(entity: actionEntity.Action) {
    const dto = new ActionDto();
    dto.id = entity.id;
    dto.gameId = entity.gameId;
    dto.actorId = entity.actorId;
    dto.status = entity.status;
    dto.round = entity.round;
    dto.actionType = entity.actionType;
    dto.phaseStart = entity.phaseStart;
    dto.phaseEnd = entity.phaseEnd;
    dto.actionPoints = entity.actionPoints;
    dto.movement = entity.movement ? ActionMovementDto.fromEntity(entity.movement) : undefined;
    dto.maneuver = entity.maneuver ? ActionManeuverDto.fromEntity(entity.maneuver) : undefined;
    dto.attacks = entity.attacks && entity.attacks.length > 0 ? entity.attacks.map((a) => ActionAttackDto.fromEntity(a)) : undefined;
    dto.fatigue = entity.fatigue;
    dto.description = entity.description;
    return dto;
  }
}

export class ActionPageDto {
  @ApiProperty({ type: [ActionDto], description: 'Actions', isArray: true })
  content: ActionDto[];

  @ApiProperty({ type: PaginationDto, description: 'Pagination information' })
  pagination: PaginationDto;
}
